<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="blatt1" nsURI="http://www.example.org/blatt1" nsPrefix="blatt1">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore.xml.type" value="http://www.eclipse.org/emf/2003/XMLType"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Name"/>
  <eSubpackages name="Repository">
    <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//Repository/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Map" eSuperTypes="#//Repository/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComplexType" eSuperTypes="#//Repository/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Date" eSuperTypes="#//Repository/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Double" eSuperTypes="#//Repository/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Repository/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Int" eSuperTypes="#//Repository/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Char" eSuperTypes="#//Repository/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Signature">
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Name"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
          eType="#//Repository/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterType" upperBound="-1"
          eType="#//Repository/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Long" eSuperTypes="#//Repository/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Float" eSuperTypes="#//Repository/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Repository/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//Repository/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Branch"/>
    <eClassifiers xsi:type="ecore:EClass" name="Interface">
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Name"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hasSignature" lowerBound="1"
          upperBound="-1" eType="#//Repository/Signature" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InternalAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="Service">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="IdenticalSignatureReturnTypes IdenticalSignatureParameterTypes"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="IdenticalSignatureReturnTypes" value="&#xA;          self.corresponds -> forAll(s | self.corresponds -> forAll(t | s.returnType = t.returnType))"/>
        <details key="IdenticalSignatureParameterTypes" value="&#xA;          self.corresponds -> forAll(s | self.corresponds -> forAll(t | s.parameterType -> includesAll(t.parameterType) and t.parameterType -> includesAll(s.parameterType)))"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="corresponds" lowerBound="1"
          upperBound="-1" eType="#//Repository/Signature" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Loop"/>
    <eClassifiers xsi:type="ecore:EClass" name="BehaviorDescription">
      <eStructuralFeatures xsi:type="ecore:EReference" name="internalActions" eType="#//Repository/InternalAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="loops" eType="#//Repository/Loop"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="branches" eType="#//Repository/Branch"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="describesInterface" upperBound="-1"
          eType="#//Repository/Interface" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="ProvidedServiceSignature ServiceRequiredIsRequired"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="ProvidedServiceSignature" value="&#xA;&#x9;&#x9;&#x9;self.providesInterface -> forAll(i | self.providesService-> exists(s | i.hasSignature->includes(s.corresponds)))"/>
        <details key="ServiceRequiredIsRequired" value="&#xA;&#x9;&#x9;&#x9;self.requiresService->forAll(s | self.requiresInterface->collect(hasSignature)->asSet()->includes(s.corresponds))"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Name"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providesInterface" upperBound="-1"
          eType="#//Repository/Interface" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiresService" lowerBound="1"
          eType="#//Repository/Service" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="behaviourDescription"
          lowerBound="1" eType="#//Repository/BehaviorDescription" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiresInterface" upperBound="-1"
          eType="#//Repository/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providesService" lowerBound="1"
          upperBound="-1" eType="#//Repository/Service"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent" eSuperTypes="#//Repository/Component">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="NoAllocation"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="NoAllocation" value="&#xA;&#x9;&#x9;&#x9;self.encapsulatesAssemblyContext->collect(isAllocatedOnContainer)->size() = 0"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulatesAssemblyContext"
          lowerBound="1" eType="#//Assembly/AssemblyContext" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Assembly">
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyContext">
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Name"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiresRole" upperBound="-1"
          eType="#//Assembly/Role" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providesRole" upperBound="-1"
          eType="#//Assembly/Role" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
          eType="#//Repository/Component" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isAllocatedOnContainer"
          lowerBound="1" eType="#//Allocation/AllocationContext"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyConnector">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="RequiredRolesFromAssemblies ProvidedRolesFromAssemblies RolesOnSameOrLinkedContainer"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="RequiredRolesFromAssemblies" value="&#xA;&#x9;&#x9;&#x9;self.requiresRole = self.requiresAssemblyContext.requiresRole"/>
        <details key="ProvidedRolesFromAssemblies" value="&#xA;&#x9;&#x9;&#x9;self.providesRole = self.providesAssemblyContext.providesRole"/>
        <details key="RolesOnSameOrLinkedContainer" value="&#xA;&#x9;&#x9;&#x9;self.providesAssemblyContext.isAllocatedOnContainer = self.requiresAssemblyContext.isAllocatedOnContainer&#xA;&#x9;&#x9;&#x9;or self.providesAssemblyContext.isAllocatedOnContainer.specifiesAllocation.links->collect(containers)->includes(self.requiresAssemblyContext.isAllocatedOnContainer)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providesAssemblyContext"
          lowerBound="1" eType="#//Assembly/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiresAssemblyContext"
          lowerBound="1" eType="#//Assembly/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiresRole" lowerBound="1"
          eType="#//Assembly/Role"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providesRole" lowerBound="1"
          eType="#//Assembly/Role"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="System">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="AllocationContextSpecifiesAssemblyAllocation AllocationOnCorrespondingEnvironment AllocationContextAssemblyContainer AssemblyContainerAllocationContext"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="AllocationContextSpecifiesAssemblyAllocation" value="&#xA;&#x9;&#x9;&#x9;self.allocationContext.alloctesAssemblies = self.encapsulatesAssemblyContext"/>
        <details key="AllocationOnCorrespondingEnvironment" value="&#xA;&#x9;&#x9;&#x9;self.allocationContext.specifiesAllocation -> forAll(c | self.environment->includes(c))"/>
        <details key="AllocationContextAssemblyContainer" value="&#xA;&#x9;&#x9;&#x9;self.allocationContext.specifiesAllocation -> forAll(c | self.encapsulatesAssemblyContext->collect(isAllocatedOnContainer)->includes(c))"/>
        <details key="AssemblyContainerAllocationContext" value="&#xA;&#x9;&#x9;&#x9;self.encapsulatesAssemblyContext->collect(isAllocatedOnContainer)->forAll(c | self.allocationContext.specifiesAllocation -> includes(c))"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulatesAssemblyContext"
          lowerBound="1" eType="#//Assembly/AssemblyContext" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="providesInterface" lowerBound="1"
          upperBound="-1" eType="#//Repository/Interface" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocationContext" lowerBound="1"
          eType="#//Allocation/AllocationContext" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
          eType="#//Environment/Environment"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Role"/>
    <eClassifiers xsi:type="ecore:EClass" name="DelegationConnector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1"
          eType="#//Assembly/Role"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
          eType="#//Repository/Interface"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Allocation">
    <eClassifiers xsi:type="ecore:EClass" name="AllocationContext">
      <eStructuralFeatures xsi:type="ecore:EReference" name="specifiesAllocation"
          upperBound="-1" eType="#//Environment/Container" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="alloctesAssemblies" lowerBound="1"
          upperBound="-1" eType="#//Assembly/AssemblyContext"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Environment">
    <eClassifiers xsi:type="ecore:EClass" name="Link">
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Name"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containers" lowerBound="2"
          upperBound="-1" eType="#//Environment/Container"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Container">
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" eType="#//Name"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="links" lowerBound="2"
          upperBound="-1" eType="#//Environment/Link"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Environment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
          upperBound="-1" eType="#//Environment/Container" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="link" upperBound="-1"
          eType="#//Environment/Link" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
