<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Repository" nsURI="platform:/resource/Blatt1/model/repository.ecore#//repository"
    nsPrefix="repository">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore.xml.type" value="http://www.eclipse.org/emf/2003/XMLType"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" lowerBound="1"
        upperBound="-1" eType="#//Signature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="IdenticalSignatureReturnTypes IdenticalSignatureParameterTypes"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="IdenticalSignatureReturnTypes" value="&#xA;          self.correspondingSignature -> forAll(s | self.correspondingSignature -> forAll(t | s.returnType = t.returnType))"/>
      <details key="IdenticalSignatureParameterTypes" value="&#xA;          self.correspondingSignature -> forAll(s | self.correspondingSignature -> forAll(t | s.parameterType -> includesAll(t.parameterType) and t.parameterType -> includesAll(s.parameterType)))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingSignature"
        lowerBound="1" upperBound="-1" eType="#//Signature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ProvidedServiceSignature ServiceRequiredIsRequired"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ProvidedServiceSignature" value="&#xA;&#x9;&#x9;&#x9;self.providedInterface -> forAll(i | self.providedService-> exists(s | i.signature->includes(s.correspondingSignature)))"/>
      <details key="ServiceRequiredIsRequired" value="&#xA;&#x9;&#x9;&#x9;self.requiredService->forAll(s | self.requiredInterface->collect(signature)->asSet()->includes(s.correspondingSignature))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterface" upperBound="-1"
        eType="#//Interface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedService" lowerBound="1"
        upperBound="-1" eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterface" upperBound="-1"
        eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredService" lowerBound="1"
        upperBound="-1" eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviourDescription" lowerBound="1"
        eType="#//BehaviorDescription" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent" eSuperTypes="#//Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NoAllocation"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NoAllocation" value="&#xA;&#x9;&#x9;&#x9;self.encapsulatedAssemblyContext->collect(allocationContext)->size() = 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulatedAssemblyContext"
        lowerBound="1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Branch"/>
  <eClassifiers xsi:type="ecore:EClass" name="InternalAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Loop"/>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviorDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalActions" eType="#//InternalAction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loops" eType="#//Loop"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" eType="#//Branch"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calledServices" upperBound="-1"
        eType="#//Service"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Map" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Date" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Double" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Int" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Char" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Signature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
        eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterType" upperBound="-1"
        eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Long" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Float" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//Type"/>
</ecore:EPackage>
