/**
 *
 * $Id$
 */
package Environment.validation;

import Environment.Container;
import Environment.Link;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Environment.SystemEnvironment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SystemEnvironmentValidator {
	boolean validate();

	boolean validateContainer(EList<Container> value);
	boolean validateLink(EList<Link> value);
}
