/**
 *
 * $Id$
 */
package Assembly.validation;

import Allocation.AllocationContext;

import Assembly.Role;

import Repository.Component;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Assembly.AssemblyContext}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssemblyContextValidator {
	boolean validate();

	boolean validateRequiredRole(EList<Role> value);
	boolean validateProvidedRole(EList<Role> value);
	boolean validateComponent(EList<Component> value);
	boolean validateAllocationContext(AllocationContext value);
	boolean validateName(String value);
}
