/**
 *
 * $Id$
 */
package Assembly.validation;

import Allocation.AllocationContext;

import Assembly.AssemblyContext;

import Environment.Environment;

import Repository.Interface;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Assembly.System}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SystemValidator {
	boolean validate();

	boolean validateEncapsulatedAssemblyContext(AssemblyContext value);
	boolean validateProvidedInterfaces(EList<Interface> value);
	boolean validateAllocationContext(AllocationContext value);
	boolean validateEnvironment(Environment value);
}
