/**
 *
 * $Id$
 */
package Allocation.validation;

import Assembly.AssemblyContext;

import Environment.Container;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Allocation.AllocationContext}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AllocationContextValidator {
	boolean validate();

	boolean validateTargetContainer(EList<Container> value);
	boolean validateAllocatedAssemblyContext(EList<AssemblyContext> value);
}
