/**
 *
 * $Id$
 */
package Repository.validation;

import Repository.BehaviorDescription;
import Repository.Interface;
import Repository.Service;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Repository.Component}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComponentValidator {
	boolean validate();

	boolean validateProvidedInterface(EList<Interface> value);
	boolean validateProvidedService(EList<Service> value);
	boolean validateRequiredInterface(EList<Interface> value);
	boolean validateRequiredService(EList<Service> value);
	boolean validateBehaviourDescription(BehaviorDescription value);
	boolean validateName(String value);
}
