/**
 *
 * $Id$
 */
package Repository.validation;

import Repository.Signature;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Repository.Service}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServiceValidator {
	boolean validate();

	boolean validateCorrespondingSignature(EList<Signature> value);
	boolean validateName(String value);
}
